apiVersion: apps/v1
kind: Deployment
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      containers:
        - name: env0-agent-trigger
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
